### ISSUE TITLE
Autotools fails

### ISSUE THREAD

**Issue by bmorris3** [AWehrhahn/SMElib#1]
Hi, 

I'm trying to install SMElib and I'm getting the following error: 
```
$ sh ./bootstrap
Usage: autoreconf [-f] [-h] [--help] [-m dir] [--macrodir=dir]
       [-l dir] [--localdir=dir] [--force] [--verbose] [--version]
```

Is there a missing part of the bootstrap command here?

**Comment by AWehrhahn** [comment]
Hi,
There are no additional commands for bootstrap. However you dont need to call it with "sh". Try just running it in the shell directly with "./bootstrap".

**Comment by AWehrhahn** [comment]
If that still doesn't work, what OS are you using?

**Comment by bmorris3** [comment]
Still doesn't work on OS X.

**Comment by AWehrhahn** [comment]
Strange, do you have the latest versions of libtools and automake installed?
libtool 2.4.6_4
automake 1.16.5

**Comment by bmorris3** [comment]
```
$ autoreconf --version
Autoconf version 2.10
$ libtool -V
Apple Inc. version cctools-921
```

**Comment by bmorris3** [comment]
All of this might not matter if I can figure out where to put the pre-built OS X files in the latest release. Mind if I ask about that, as well? Where do I put those files?

**Comment by AWehrhahn** [comment]
In PySME?
They go in src/pysme/lib/
with the datafiles in src/pysme/share/

inside the PySME installation

PySME should download the latest release automatically if no library files are present there

**Comment by AWehrhahn** [comment]
For reference I install libtool and automake on MAC OSX using homebrew. I don't know if those are different versions from those you have installed or not.

**Comment by bmorris3** [comment]
Oh interesting, I'm getting the following error when I try the minimum example in PySME: 
```
(base) menelaus:examples brettmorris$ python minimum.py
running build_ext
building '_smelib' extension
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules winreg, win32api or win32con are installed.
C compiler: x86_64-apple-darwin13.4.0-clang -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem //anaconda3/include -D_FORTIFY_SOURCE=2 -isystem //anaconda3/include

compile options: '-I//anaconda3/lib/python3.7/site-packages/numpy/core/include -I/anaconda3/lib/python3.7/site-packages/pysme/lib -I//anaconda3/include/python3.7m -c'
x86_64-apple-darwin13.4.0-clang: _smelib.cpp
x86_64-apple-darwin13.4.0-clang++ -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,//anaconda3/lib -L//anaconda3/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,//anaconda3/lib -L//anaconda3/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,//anaconda3/lib -L//anaconda3/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem //anaconda3/include -D_FORTIFY_SOURCE=2 -isystem //anaconda3/include -arch x86_64 build/temp.macosx-10.9-x86_64-3.7/_smelib.o -L/anaconda3/lib/python3.7/site-packages/pysme/lib -lsme -o /anaconda3/lib/python3.7/site-packages/pysme/smelib/_smelib.cpython-37m-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
Traceback (most recent call last):
  File "minimum.py", line 11, in <module>
    from pysme import sme as SME
  File "//anaconda3/lib/python3.7/site-packages/pysme/sme.py", line 19, in <module>
    from .linelist.linelist import LineList
  File "//anaconda3/lib/python3.7/site-packages/pysme/linelist/linelist.py", line 18, in <module>
    from ..util import air2vac, vac2air
  File "//anaconda3/lib/python3.7/site-packages/pysme/util.py", line 25, in <module>
    from .sme_synth import SME_DLL
  File "//anaconda3/lib/python3.7/site-packages/pysme/sme_synth.py", line 20, in <module>
    from .smelib import _smelib
ImportError: dlopen(//anaconda3/lib/python3.7/site-packages/pysme/smelib/_smelib.cpython-37m-darwin.so, 2): Library not loaded: /Users/runner/work/SMElib/SMElib/lib/libsme.5.dylib
  Referenced from: //anaconda3/lib/python3.7/site-packages/pysme/smelib/_smelib.cpython-37m-darwin.so
  Reason: image not found
```
It looks to me like smelib isn't being automatically downloaded, would you agree?

**Comment by AWehrhahn** [comment]
The SME library is being downloaded, but it fails in compiling the interface to the library.

Have you tried installing the Python modules it mentions?
winreg, win32api or win32con

**Comment by AWehrhahn** [comment]
Actually what confuses me, is why would it look for Windows specific packages, when you are using a Mac?

**Comment by bmorris3** [comment]
I have no idea, I'm confused too. 😅

**Comment by AWehrhahn** [comment]
Now that I read it again, you might be right about the missing files.
Did the sme library get downloaded to src/pysme/lib ?
Is there a "libsme.5.dylib" file?

**Comment by bmorris3** [comment]
It did not get downloaded, but I put it there by hand. There is a libsme.5.dylib file there.

**Comment by AWehrhahn** [comment]
hmm, weird, and it did not give an error message either?

Does it still fail running minimum.py ?

**Comment by AWehrhahn** [comment]
If it does can you try putting the library at this location: "/Users/runner/work/SMElib/SMElib/lib/libsme.5.dylib"

**Comment by bmorris3** [comment]
No error message on install, and yes minimum.py fails:
```
$ pip install .
Processing /Users/brettmorris/git/SME
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: wget in /anaconda3/lib/python3.7/site-packages (from pysme-astro==0.4.121+0.g2021b92.dirty) (3.2)
Requirement already satisfied: colorlog in /anaconda3/lib/python3.7/site-packages (from pysme-astro==0.4.121+0.g2021b92.dirty) (6.6.0)
Requirement already satisfied: astropy in /anaconda3/lib/python3.7/site-packages (from pysme-astro==0.4.121+0.g2021b92.dirty) (4.3.1)
Requirement already satisfied: flex-format in /anaconda3/lib/python3.7/site-packages (from pysme-astro==0.4.121+0.g2021b92.dirty) (0.2.18)
Requirement already satisfied: numpy in /anaconda3/lib/python3.7/site-packages (from pysme-astro==0.4.121+0.g2021b92.dirty) (1.21.3)
Requirement already satisfied: tqdm in /anaconda3/lib/python3.7/site-packages (from pysme-astro==0.4.121+0.g2021b92.dirty) (4.60.0)
Requirement already satisfied: scipy in /anaconda3/lib/python3.7/site-packages (from pysme-astro==0.4.121+0.g2021b92.dirty) (1.7.1)
Requirement already satisfied: pybtex in /anaconda3/lib/python3.7/site-packages (from pysme-astro==0.4.121+0.g2021b92.dirty) (0.24.0)
Requirement already satisfied: pandas in /anaconda3/lib/python3.7/site-packages (from pysme-astro==0.4.121+0.g2021b92.dirty) (1.2.4)
Requirement already satisfied: emcee in /anaconda3/lib/python3.7/site-packages/emcee-3.0rc2-py3.7.egg (from pysme-astro==0.4.121+0.g2021b92.dirty) (3.0rc2)
Requirement already satisfied: pyerfa>=1.7.3 in /anaconda3/lib/python3.7/site-packages (from astropy->pysme-astro==0.4.121+0.g2021b92.dirty) (2.0.0)
Requirement already satisfied: importlib-metadata in /anaconda3/lib/python3.7/site-packages (from astropy->pysme-astro==0.4.121+0.g2021b92.dirty) (3.10.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /anaconda3/lib/python3.7/site-packages (from pandas->pysme-astro==0.4.121+0.g2021b92.dirty) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /anaconda3/lib/python3.7/site-packages (from pandas->pysme-astro==0.4.121+0.g2021b92.dirty) (2021.1)
Requirement already satisfied: latexcodec>=1.0.4 in /anaconda3/lib/python3.7/site-packages (from pybtex->pysme-astro==0.4.121+0.g2021b92.dirty) (2.0.1)
Requirement already satisfied: PyYAML>=3.01 in /anaconda3/lib/python3.7/site-packages (from pybtex->pysme-astro==0.4.121+0.g2021b92.dirty) (5.4.1)
Requirement already satisfied: six in /anaconda3/lib/python3.7/site-packages (from pybtex->pysme-astro==0.4.121+0.g2021b92.dirty) (1.15.0)
Requirement already satisfied: zipp>=0.5 in /anaconda3/lib/python3.7/site-packages (from importlib-metadata->astropy->pysme-astro==0.4.121+0.g2021b92.dirty) (3.4.1)
Requirement already satisfied: typing-extensions>=3.6.4 in /anaconda3/lib/python3.7/site-packages (from importlib-metadata->astropy->pysme-astro==0.4.121+0.g2021b92.dirty) (3.7.4.3)
Building wheels for collected packages: pysme-astro
  Building wheel for pysme-astro (pyproject.toml) ... done
  Created wheel for pysme-astro: filename=pysme_astro-0.4.121+0.g2021b92.dirty-py3-none-any.whl size=6080757 sha256=68df874f5a6cb9cc5f44b2da2992252cd7745279284a88b8d674db982e76f962
  Stored in directory: /private/var/folders/48/n6t36qp16gs3hhlpjwrwx5r80000gn/T/pip-ephem-wheel-cache-g0tx8bpl/wheels/e6/58/94/f80237779a4937660811bc130f9d9ac9776ad9768627f19d6b
Successfully built pysme-astro
Installing collected packages: pysme-astro
Successfully installed pysme-astro-0.4.121+0.g2021b92.dirty
(base) menelaus:SME brettmorris$ cd examples
(base) menelaus:examples brettmorris$ python minimum.py
running build_ext
building '_smelib' extension
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules winreg, win32api or win32con are installed.
C compiler: x86_64-apple-darwin13.4.0-clang -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem //anaconda3/include -D_FORTIFY_SOURCE=2 -isystem //anaconda3/include

creating build
creating build/temp.macosx-10.9-x86_64-3.7
compile options: '-I//anaconda3/lib/python3.7/site-packages/numpy/core/include -I/anaconda3/lib/python3.7/site-packages/pysme/lib -I//anaconda3/include/python3.7m -c'
x86_64-apple-darwin13.4.0-clang: _smelib.cpp
x86_64-apple-darwin13.4.0-clang++ -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,//anaconda3/lib -L//anaconda3/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,//anaconda3/lib -L//anaconda3/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,//anaconda3/lib -L//anaconda3/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem //anaconda3/include -D_FORTIFY_SOURCE=2 -isystem //anaconda3/include -arch x86_64 build/temp.macosx-10.9-x86_64-3.7/_smelib.o -L/anaconda3/lib/python3.7/site-packages/pysme/lib -lsme -o /anaconda3/lib/python3.7/site-packages/pysme/smelib/_smelib.cpython-37m-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
Traceback (most recent call last):
  File "minimum.py", line 11, in <module>
    from pysme import sme as SME
  File "//anaconda3/lib/python3.7/site-packages/pysme/sme.py", line 19, in <module>
    from .linelist.linelist import LineList
  File "//anaconda3/lib/python3.7/site-packages/pysme/linelist/linelist.py", line 18, in <module>
    from ..util import air2vac, vac2air
  File "//anaconda3/lib/python3.7/site-packages/pysme/util.py", line 25, in <module>
    from .sme_synth import SME_DLL
  File "//anaconda3/lib/python3.7/site-packages/pysme/sme_synth.py", line 20, in <module>
    from .smelib import _smelib
ImportError: dlopen(//anaconda3/lib/python3.7/site-packages/pysme/smelib/_smelib.cpython-37m-darwin.so, 2): Library not loaded: /Users/runner/work/SMElib/SMElib/lib/libsme.5.dylib
  Referenced from: //anaconda3/lib/python3.7/site-packages/pysme/smelib/_smelib.cpython-37m-darwin.so
  Reason: image not found
(base) menelaus:examples brettmorris$
```

**Comment by bmorris3** [comment]
> /Users/runner/work/SMElib/SMElib/lib/

I would have tried this but I get the following error when the process is finished: 
```
$ ls /Users/runner/work/SMElib/SMElib/lib/
ls: /Users/runner/work/SMElib/SMElib/lib/: No such file or directory
```
I think the task cleans that dir when the process fails.

**Comment by AWehrhahn** [comment]
ah, instead of "pip install ." Try adding the -e flag, so "pip install -e ."
I don't think the library is being copied during install

**Comment by bmorris3** [comment]
That took longer to run but produces the same error.

**Comment by AWehrhahn** [comment]
Can you make the "/Users/runner/work/SMElib/SMElib/lib/" directory and put the libsme.5.dylib file in there?
Or maybe make it a symbolic link?
I don't understand why it tries to look there at all, but it seems to expect the library there

**Comment by bmorris3** [comment]
I'd have to make a user called runner to do that, there must be another way...

**Comment by bmorris3** [comment]
Here's a fresh attempt without building anything from source: 
```
(base) menelaus:examples brettmorris$ pip install pysme-astro
\Collecting pysme-astro
  Using cached pysme_astro-0.4.121-py3-none-any.whl (226 kB)
Requirement already satisfied: emcee in /anaconda3/lib/python3.7/site-packages/emcee-3.0rc2-py3.7.egg (from pysme-astro) (3.0rc2)
Requirement already satisfied: numpy in /anaconda3/lib/python3.7/site-packages (from pysme-astro) (1.21.3)
Requirement already satisfied: scipy in /anaconda3/lib/python3.7/site-packages (from pysme-astro) (1.7.1)
Requirement already satisfied: pandas in /anaconda3/lib/python3.7/site-packages (from pysme-astro) (1.2.4)
Requirement already satisfied: colorlog in /anaconda3/lib/python3.7/site-packages (from pysme-astro) (6.6.0)
Requirement already satisfied: wget in /anaconda3/lib/python3.7/site-packages (from pysme-astro) (3.2)
Requirement already satisfied: tqdm in /anaconda3/lib/python3.7/site-packages (from pysme-astro) (4.60.0)
Requirement already satisfied: pybtex in /anaconda3/lib/python3.7/site-packages (from pysme-astro) (0.24.0)
Requirement already satisfied: flex-format in /anaconda3/lib/python3.7/site-packages (from pysme-astro) (0.2.18)
Requirement already satisfied: astropy in /anaconda3/lib/python3.7/site-packages (from pysme-astro) (4.3.1)
Requirement already satisfied: pyerfa>=1.7.3 in /anaconda3/lib/python3.7/site-packages (from astropy->pysme-astro) (2.0.0)
Requirement already satisfied: importlib-metadata in /anaconda3/lib/python3.7/site-packages (from astropy->pysme-astro) (3.10.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /anaconda3/lib/python3.7/site-packages (from pandas->pysme-astro) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /anaconda3/lib/python3.7/site-packages (from pandas->pysme-astro) (2021.1)
Requirement already satisfied: latexcodec>=1.0.4 in /anaconda3/lib/python3.7/site-packages (from pybtex->pysme-astro) (2.0.1)
Requirement already satisfied: PyYAML>=3.01 in /anaconda3/lib/python3.7/site-packages (from pybtex->pysme-astro) (5.4.1)
Requirement already satisfied: six in /anaconda3/lib/python3.7/site-packages (from pybtex->pysme-astro) (1.15.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /anaconda3/lib/python3.7/site-packages (from importlib-metadata->astropy->pysme-astro) (3.7.4.3)
Requirement already satisfied: zipp>=0.5 in /anaconda3/lib/python3.7/site-packages (from importlib-metadata->astropy->pysme-astro) (3.4.1)
Installing collected packages: pysme-astro
Successfully installed pysme-astro-0.4.121
(base) menelaus:examples brettmorris$ python minimum.py
Downloading and installing the latest libsme version for this system
Downloading file https://github.com/AWehrhahn/SMElib/releases/latest/download/macos-gfortran.zip
100% [..........................................................................] 5863289 / 5863289running build_ext
building '_smelib' extension
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules winreg, win32api or win32con are installed.
C compiler: x86_64-apple-darwin13.4.0-clang -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem //anaconda3/include -D_FORTIFY_SOURCE=2 -isystem //anaconda3/include

compile options: '-I//anaconda3/lib/python3.7/site-packages/numpy/core/include -I/anaconda3/lib/python3.7/site-packages/pysme/lib -I//anaconda3/include/python3.7m -c'
x86_64-apple-darwin13.4.0-clang: _smelib.cpp
x86_64-apple-darwin13.4.0-clang++ -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,//anaconda3/lib -L//anaconda3/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,//anaconda3/lib -L//anaconda3/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,//anaconda3/lib -L//anaconda3/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem //anaconda3/include -D_FORTIFY_SOURCE=2 -isystem //anaconda3/include -arch x86_64 build/temp.macosx-10.9-x86_64-3.7/_smelib.o -L/anaconda3/lib/python3.7/site-packages/pysme/lib -lsme -o /anaconda3/lib/python3.7/site-packages/pysme/smelib/_smelib.cpython-37m-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
Traceback (most recent call last):
  File "minimum.py", line 11, in <module>
    from pysme import sme as SME
  File "//anaconda3/lib/python3.7/site-packages/pysme/sme.py", line 19, in <module>
    from .linelist.linelist import LineList
  File "//anaconda3/lib/python3.7/site-packages/pysme/linelist/linelist.py", line 18, in <module>
    from ..util import air2vac, vac2air
  File "//anaconda3/lib/python3.7/site-packages/pysme/util.py", line 25, in <module>
    from .sme_synth import SME_DLL
  File "//anaconda3/lib/python3.7/site-packages/pysme/sme_synth.py", line 20, in <module>
    from .smelib import _smelib
ImportError: dlopen(//anaconda3/lib/python3.7/site-packages/pysme/smelib/_smelib.cpython-37m-darwin.so, 2): Library not loaded: /Users/runner/work/SMElib/SMElib/lib/libsme.5.dylib
  Referenced from: //anaconda3/lib/python3.7/site-packages/pysme/smelib/_smelib.cpython-37m-darwin.so
  Reason: image not found
  ```
  You can see it's downloading smelib successfully, then looking for windows packages and failing.

**Comment by bmorris3** [comment]
I just tried installing on a different Mac OS X machine and I'm getting the same error.

**Comment by AWehrhahn** [comment]
Yeah, I just tried it on another Mac OS X and it gave the same result. For some reason it changes the path of the expected library (I think). I am currently trying to figure out how to fix that.

**Comment by bmorris3** [comment]
Thanks so much for your rapid responses! I'm looking forward to figuring out what's going on 😄

**Comment by AWehrhahn** [comment]
So as far as I can tell, in Mac OSX the dylib includes an absolute path for where it was compiled. And if that doesn't match the current location and name it fails with the error we are getting. 

It should in theory be possible to set the environment variable DYLD_LIBRARY_PATH or DYLD_FALLBACK_LIBRARY_PATH to the correct directory (see also https://stackoverflow.com/questions/3146274/is-it-ok-to-use-dyld-library-path-on-mac-os-x-and-whats-the-dynamic-library-s). However I have so far failed to get it to work.

Alternatively it should also be possible to change the name in the dylib using "install_name_tool -change smelib.5.dylib ./sme_synth.so.darwin.x86_64.64 sme_synth.so.darwin.x86_64.64". But again this has failed me so far.

I will keep trying and let you know, when I get a working solution

**Comment by AWehrhahn** [comment]
I got it to work on my end. The problem was indeed the path hardcoded in the dylibs. These can be changed with 
```
  install_name_tool -id $PWD/libsme.5.dylib libsme.5.dylib
  install_name_tool -id $PWD/libsme.dylib libsme.dylib
  install_name_tool -id $PWD/sme_synth.so.darwin.x86_64.64 sme_synth.so.darwin.x86_64.64
```
inside the folder PySME is installed at.

**Comment by bmorris3** [comment]
Should I run those lines before or after installing? Neither seem to work for me.

**Comment by AWehrhahn** [comment]
The lines should be in-between, i suppose. I.e. update the C libraries, but then recompile the interface by removing the _smelib...so in src/pysme/smelib
I updated PySME so that it should do that automatically when it is run for the first time.
________________________________

**Comment by AWehrhahn** [comment]
To be specific you want to do something like this:
```
# Go to your installation (usually in site-packages, unless we installed PySME with the -e option)
cd src/pysme/smelib
python -c "from libtools import download_libsme; download_libsme()"
cd ../lib
install_name_tool -id $PWD/libsme.5.dylib libsme.5.dylib
install_name_tool -id $PWD/libsme.dylib libsme.dylib
install_name_tool -id $PWD/sme_synth.so.darwin.x86_64.64 sme_synth.so.darwin.x86_64.64
cd ../smelib
python -c "from libtools import compile_interface; compile_interface()"
```

**Comment by AWehrhahn** [comment]
Does this work for you now?

**Comment by bmorris3** [comment]
Yes thank you! Now I just have to learn from the docs how to use it.

**Comment by AWehrhahn** [comment]
If you have any questions, I will be happy to help
